### PR TITLE
add scale14 to global params

### LINKED ISSUE #36: cannot optimize `scale14` with DoubleExponential
Attached a minimal FB input for reproducing the case. I can optimize `scale14` in regular vdW non-bonded FF (Sage) but not with the DoubleExponential functional form. Edit: The gradient is always zero with DoubleExponential form for scale14.

The following additions to the file [handlers/nonbonded.py](https://github.com/openforcefield/smirnoff-plugins/blob/main/smirnoff_plugins/handlers/nonbonded.py#L389) fixed it, I don't know if both the changes are needed or just adding the parameter attribute is enough
```
at line397: scale14 = ParameterAttribute(default=0.5)
at line453: global_parameters = ["alpha", "beta", "scale14"]

```

[dexp-opt-scale14.tar.gz](https://github.com/openforcefield/smirnoff-plugins/files/9271162/dexp-opt-scale14.tar.gz)

cc: @jthorton @j-wags

### PR DESCRIPTION
**Pull request by pavankum**
## Description
To resolve #36 

## Status
- [ ] Ready to go

### CODE REVIEW

**Review by mattwthompson — APPROVED** [review]
This seems good to me - based on how I understand the code to work and you reporting that it works in the linked issue.

In principle there should be tests, etc., but seeing as
* this is more of an experimental repo than a production-facing one
* this has already been tested in some capacity (all the way to getting results!)
* branches diverging is undesirable
* I see a 👍 from @jthorton

I think we should merge this as-is - and we should pull the trigger in a day or two if no more comments.

**Comment by jthorton** [comment]
@pavankum thanks for looking into this, I was a little lost as to why this fixed the issue as the `scale14` parameter is already added to the global parameter list explicitly in the creation of the custom bond force which holds the 1-4 interactions [here](https://github.com/openforcefield/smirnoff-plugins/blob/fffd379c049bd90f6ca016c228115d5e8260faf7/smirnoff_plugins/handlers/nonbonded.py#L269). It seems like the root cause of this is in forcebalance when it creates a [copy of the system](https://github.com/leeping/forcebalance/blob/9f994646ef82ccdb80c0a56ba4937fe77334f27d/src/openmmio.py#L413) to evaluate the perturbed parameters it only looks for global values in the `CustomNonbondedForce` but if it also checked the `CustomBondForce` it would copy both.

**Comment by jthorton** [comment]
I think it's probably easier to fix this here but I have suggested the fix upstream to forcebalance [here](https://github.com/leeping/forcebalance/pull/263), feel free to do the fits using this branch @pavankum  as it will take a while to get a new forcebalance version.

**Comment by pavankum** [comment]
Ahh okay, thank you @jthorton for fixing it in FB. Thank you for the review @mattwthompson, since this is fixed in FB I think we need not merge this in master.

**Comment by mattwthompson** [comment]
Do these patches conflict with each other? All things being equal I'd rather have it here since we have more control over the release cycle and it's easier to pin (well, add a lower constraint) this package than ForceBalance.

**Comment by pavankum** [comment]
Yeah, I think we would be double counting the contributions if both patches are applied. I can still work from this branch and it's not a blocker for me. I would leave it to you and @jthorton to decide what's the best way forward.

**Comment by jthorton** [comment]
I agree it would be easier to fix here and this will fix our pathway of using forcebalance with systems made via the toolkit but will leave it broken for anyone using custom forces via OpenMM xmls, although I don't think that is very common at all! So feel free to merge and Ill leave my FB PR for now and see what happens.

**Review by jthorton — APPROVED** [review]

**Comment by mattwthompson** [comment]
Sounds good to me. Let me know if you want this in a release (0.0.3), otherwise I assume you and @pavankum can keep running experiments from the `main` branch as useful

**Pull request merged**
