### PR TITLE
Add missing vsite exclusions

### LINKED ISSUE #40: V-sites missing exclusions with toolkit refactor
After the v-site refactor in the toolkit v-site exclusions are generated after all of the handlers have been called rather than during the v-site handler,  the custom forces here can no longer copy the exclusions. Instead, we need to work them out probably using the same logic in this [function](https://github.com/openforcefield/openff-toolkit/blob/5887e1f1cb8408ea7548650d19d12acdaed9cc7e/openff/toolkit/typing/engines/smirnoff/forcefield.py#L1340).

### PR DESCRIPTION
**Pull request by jthorton**
## Description
Fixes #40 by adding missing bonds between v-sites and parent atom neighbours to the topology before calling `createExclusionsFromBonds` on the custom force. Exclusions between sites on the same atom are also added.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [X] add tests
  - [ ] pin toolkit version in new release

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Review by j-wags — COMMENTED** [review]
I've looked at this for about 30 minutes and I can't say that I fully follow this code (even in its original state), but let me know if you'd like help recruiting a reviewer.

**Comment by jthorton** [comment]
@j-wags thanks for taking a look over it, I agree I wasn't sure what was happening but I have managed to simplify it ever so slightly by removing the double counting of some topology bonds (that confused me for a while). The code is now trying to add a bond between each v-site and the neighbour of the parent to ensure they get the same exclusions as they have the same bonds. A review would be great so we can stay up to date with the 10-x line of the toolkit.

**Comment by mattwthompson** [comment]
I can take over reviewing this (I'm working on a parallel implementation right now, actually). An edge case that I come across often is making virtual sites on nearby atoms (but not the same parent) are excluded from each other, i.e.

```
A0 - A1 - A2 - A3 - A4
     |         |
     V1        V3
```

Virtual sites `V1` and `V3` (with parent atoms `A1` and `A3`) are easy to miss if only adding exceptions based on the atoms a parent interacts with.

**Comment by jthorton** [comment]
Interesting I hadn't thought about this case but I would expect it to be handled by `createExclusionsFromBonds` as long as the bonds V1-A2 and V3-A2 are in the list as it should see them as forming an angle. Ill try and add a test for this case to make sure though.

**Comment by j-wags** [comment]
Yeah, I think Josh is right above - The case that Matt showed should be handled just fine by the current code.

(not blocking) The thing that mostly confuses me about the initial state of this code was how it:

1. collected all the bonds
2. made exceptions from bonds (in a world without vsites, I'd think it'd just be done here)
3. Looked at the existing OpenMM NonbondedForce
4. Compared the CustomNonbondedForce's exceptions to the NonbondedForce's exceptions (I guess since the NonbondedForce knows about vsites)
5. Added any exceptions that are in the NonbondedForce but not the CustomNonbondedForce to the CustomNonbondedForce

My confusion was that steps 1-2 seem to be unnecessary/redundant if we're already doing steps 3-5. So I'm thinking that I must be missing something fundamental about how this works.

**Review by mattwthompson — COMMENTED** [review]
I've skimmed through the code and I like the approach. I don't have any suggested changes, but I do think adding a couple of tests would be useful. I wrote up a [couple](https://github.com/openforcefield/openff-interchange/blob/42ae132ff7593090c4c0346d0d95fad4664299a2/openff/interchange/tests/interoperability_tests/test_openmm.py#L475-L547) (more are needed)  in Interchange that you are welcome to nab. They could be written more concisely, but they cover at least most of the basic behaviors. The dichloroethane test was an attempt to check that 1-4 interactions are handled properly. I'll let you decide if you want to write up the case in my [earlier comment](https://github.com/openforcefield/smirnoff-plugins/pull/41#issuecomment-1219613008) as a test - I am convinced this should work after you explained it, but more tests wouldn't hurt.

**Comment by mattwthompson** [comment]
I ran into something I think related to #40 while working on #46, and merging this in got the simulations running.

**Pull request merged**
